apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend  # Deployment的名字，用于在Kubernetes内部唯一标识这个Deployment资源。
spec:
  replicas: 1  # 指定期望的Pod副本数量为2。
  selector:
    matchLabels:
      app: frontend  # 选择器，用于找到应该由此Deployment管理的Pod。只有标签匹配此处定义的Pod会被管理。
  template:
    metadata:
      labels:
        app: frontend  # Pod模板的标签，确保创建的Pod被上面的selector正确选择。
    spec:
      containers:
      - name: container1  # 容器的名称，在Pod内必须唯一。
        image: henrylong280/my-simple-server:latest  # 容器使用的镜像。
        
        command: ["/bin/bash", "/start.sh"]
        args: ["http://34.162.123.130:8888/", "http://34.162.101.87:50070/", "http://34.162.37.65:4040/", "http://34.23.252.182:8080/", "http://34.139.35.121:9000"] # docker run命令时紧跟在镜像名称后面指定的命令行参数
