apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop
  labels:
    app: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop
  template:
    metadata:
      labels:
        app: hadoop
    spec:
      containers:
      - name: container1
        image: harisekhon/hadoop
        ports:
        - containerPort: 8042
          name: nodemanager
        - containerPort: 8088
          name: resourcemanager
        - containerPort: 19888
          name: job
