apiVersion: v1
kind: Service
metadata:
  name: hadoop
  labels:
    app: hadoop
spec:
  type: LoadBalancer
  ports:
  - name: nodemanager
    port: 8042
    targetPort: 8042
  - name: resourcemanager
    port: 8088
    targetPort: 8088
  - name: jobhistory
    port: 19888
    targetPort: 19888
  - name: namenode-ui
    port: 50070
    targetPort: 50070
  - name: datanode-ui
    port: 50075
    targetPort: 50075
  selector:
    app: hadoop
